added a description to the readme file
Richez003/PORTFOLIO pull request #1
Opened 2022-03-19 20:35 UTC by Richez003

created a portfolio using the ;
correct github flow
run linters to check for errors
crated a new branch

2022-03-19 22:32 UTC, VICTOR-CHUKWU requested changes
Hi @Richez003 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 22:32 UTC, VICTOR-CHUKWU commented on index.html
> +        <h2 class="h2">Welcome</h2>
- [ ] According to the project requirement this logo should be inside `<a>` tag, this is for easy navigation when you are not in home page, kindly fix this

2022-03-19 22:32 UTC, VICTOR-CHUKWU commented on index.html
> +                <li><img src="./images/angellist.png" alt="angellist"></li>
- [ ] Kindly put your images in an `a` tag so as to navigate to your social media when clicked. it should look like this ` <li><a href=''><img src="./images/twitter.png" alt="twitter"></a></li>`

2022-03-21 08:02 UTC, moise10r approved these changes
### Hi @Richez003 , 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 08:08 UTC, moise10r commented on index.html
> +                </span>
- [ OPTIONAL] Kindly make this down icon to be responsive for all mobile versions size :arrow_down: 

![fool](https://user-images.githubusercontent.com/57562869/159223799-53c2ab02-b201-491e-9522-7cb6e698a9ba.png)

2022-03-21 08:09 UTC, merged