Screen popup
Richez003/PORTFOLIO pull request #12
Opened 2022-04-14 16:58 UTC by Richez003

popup design

2022-04-14 18:24 UTC, brytebee requested changes
Hi, Team👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- No linter errors.✔️
- Desktop popup works excellent. ✔️
- Correctly used JS to dynamically populate the popup. ✔️
- Good handling and use of JS array of objects. ✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 18:24 UTC, brytebee commented on index.html
>  <body>
- [ ] **Optional:** Kindly note that commits messages should always be written as proper English sentences. This keeps your documentation and works uniform and professional.

![image](https://user-images.githubusercontent.com/27709832/163449908-f0dbc5c6-ae55-4bf7-b7c2-857ce7315b6a.png)

2022-04-14 18:24 UTC, brytebee commented on index.html
> +    </div> -->
- [ ] **Required:** You have done an amazing job so far. However, the mobile view popup has some issues that need to be fixed.

![popup](https://user-images.githubusercontent.com/27709832/163452428-4a5c9798-a560-487b-9628-a91f25325743.gif)

_**Hint**_
- You could reduce the height of the popup container.
- You can also truncate the text to a given length.
- You could hide the scroll `overflow`

2022-04-14 18:24 UTC, brytebee commented on index.html
> +
- [x] **Required:** Kindly remove commented out code. It is unprofessional to push them.

2022-04-15 14:23 UTC, Richez003 commented on index.html
> +
done that sir

2022-04-15 14:24 UTC, Richez003 commented on index.html
> +    </div> -->
I have reduced the height as requested .
truncated the text.
And hide scroll overflow.

2022-04-15 15:59 UTC, topeogunleye approved these changes
### Hi Team,
Great job on this project 👍🏻
# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! 
There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
>
### To Highlight
- [x]  Used GitHub Workflow :heavy_check_mark: 
>
> ## [Optional] suggestions:
> Please work on the mobile responsiveness of your website. Your project pop up is overflowing horizontally on Mobile:

https://user-images.githubusercontent.com/52934128/163592812-5573eab8-b078-4a1d-bca5-c76275865167.mp4
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-15 23:45 UTC, merged